name: CodeQL

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.17'
      
 #     - name: go build
 #       run: go build ./...  
  
  codeql-go:
    uses: chargehound/security-workflows-public/.github/workflows/codeql-go.yml@main
    with:
      build-mode: "manual"
      build-command: "go build ./..."
